[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Ensure static files from public folder are accessible
[[redirects]]
  from = "/logo.png"
  to = "/logo.png"
  status = 200
  force = false

[[redirects]]
  from = "/logo2.svg"
  to = "/logo2.svg"
  status = 200
  force = false

# Static file handling for images
[[headers]]
  for = "/logo.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/png"
    
[[headers]]
  for = "/logo2.svg"  
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/svg+xml"